version: '3.7'
services:
  offers_consumer:
    image: offer_reader
    container_name: offer_reader
    volumes:
      - ./reader:/app/reader
    command: ["python", "/app/reader/listener.py"]
    env_file:
      - .env
  store:
    image: offer_store
    container_name: offer_store
    volumes:
      - ./store:/app/store
  db:
    container_name: offers_db
    image: postgres:9.5.2
    volumes:
      - develop_offers_db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
networks:
  default:
    external:
      name: develop_offers
volumes:
  develop_offers_db:
    external: true